---
title: "FunctEnrich"
author: "Lydia Fortea"
date: "8/6/2018"
output: pdf_document
---

```{r setup, cache=FALSE, echo=FALSE, results='hide', message=FALSE}
library(knitr)
library(SummarizedExperiment)
library(edgeR)
library(geneplotter)
library(sva)
library(corpcor)

opts_chunk$set(cache=TRUE,
               cache.path="cache/file2",
               cache.extra=R.version.string,
               autodep=TRUE,
               fig.align="center",
               comment="")

thca <- readRDS(file.path("raw_counts", "seTHCA.rds"))
dge <- readRDS(file.path("results", "dge.rds"))
thca.filt.unnorm <- readRDS(file.path("results", "thca.filt.unnorm.rds"))
dge.filt.unnorm <- readRDS(file.path("results", "dge.filt.unnorm.rds"))
thca.filt <- readRDS(file.path("results", "thca.filt4.rds"))
dge.filt <- readRDS(file.path("results", "dge.filt4.rds"))
DEgenes <- readRDS("DEgenes.rds")
```

Gene Ontology 
```{r}
library(org.Hs.eg.db)
allHumanGO <- select(org.Hs.eg.db, columns = "GO", key = keys(org.Hs.eg.db, keytype = "SYMBOL"), keytype = "SYMBOL")
dim(allHumanGO)
geneUniverse <- rownames(thca)
length(geneUniverse)
```


```{r}
data(c2BroadSets)
c2BroadSets <- c2BroadSets[c(grep("^KEGG", names(c2BroadSets)),
               grep("^REACTOME", names(c2BroadSets)), grep("^BIOCARTA", names(c2BroadSets)))]
c2BroadSets
gsc <- GeneSetCollection(c(c2BroadSets, GeneSet(rownames(DEgenes))))
gsc
```

```{r}
gsc <- mapIdentifiers(gsc, AnnoOrEntrezIdentifier(metadata(thca.filt)$annotation))
gsc
Im <- incidence(gsc)
dim(Im)
Im <- Im[, colnames(Im) %in% rownames(thca.filt)]
dim(Im)
thca.filt <- thca.filt[colnames(Im), ]
dim(thca.filt)
dge <- dge[colnames(Im), ]
dim(dge)
```

```{r}
thca.filt$type <- relevel(thca.filt$type, ref = "tumor")
mod <- model.matrix(~type, data = colData(thca.filt))
mod0 <- model.matrix(~1, colData(thca.filt))
sv <- sva(assays(thca.filt)$logCPM, mod = mod, mod0 = mod0)
mod <- cbind(mod, sv$sv)
colnames(mod) <- c(colnames(mod)[1:2], paste0("SV", 1:sv$n))
sample_id <- substr(colnames(thca.filt), 9, 12)
colData(thca.filt)$sample_id <- factor(sample_id)
corfit <- duplicateCorrelation(assays(thca.filt)$logCPM, mod, block = thca.filt$sample_id)
fit <- lmFit(assays(thca.filt)$logCPM, mod, block = thca.filt$sample_id, correlation = corfit$consensus)
fit <- eBayes(fit, trend = TRUE)
tt <- topTable(fit, coef = 2, n = Inf)
#head(tt, n=20)
qq <- qqnorm(tt$t)
abline(0, 1, col="purple")
chroutliers <- tt$chr[abs(tt$t) > 10]
text(qq$x[abs(qq$y) > 10], qq$y[abs(qq$y) > 10], chroutliers, pos = 4)
```

```{r}
Im <- Im[rowSums(Im) >= 5, ]
dim(Im)
tGSgenes <- tt[match(colnames(Im), rownames(tt)), "t"]
length(tGSgenes)
head(tGSgenes)
zS <- sqrt(rowSums(Im)) * (as.vector(Im %*% tGSgenes)/rowSums(Im))
length(zS)
head(zS)
qqnorm(zS, col = "orange2")
abline(0, 1, col = "orchid3")
rnkGS <- sort(abs(zS), decreasing = TRUE)
head(rnkGS)
plotGS <- function(se, gs, pheno, ...) {
    l <- levels(colData(se)[, pheno])
    idxSamples1 <- colData(se)[, pheno] == l[1]
    idxSamples2 <- colData(se)[, pheno] == l[2]
    exps1 <- rowMeans(assays(se)$logCPM[gs, idxSamples1])
    exps2 <- rowMeans(assays(se)$logCPM[gs, idxSamples2])
    rng <- range(c(exps1, exps2))
    plot(exps1, exps2, pch = 21, col = "black", bg = "black", xlim = rng, ylim = rng, 
        xlab = l[1], ylab = l[2], ...)
    abline(a = 0, b = 1, lwd = 2, col = "red")
}#mean of expression per gene
genesGS1 <- colnames(Im)[which(Im[names(rnkGS)[2], ] == 1)]
genesGS2 <- colnames(Im)[which(Im[names(rnkGS)[3], ] == 1)]
par(mfrow = c(1, 2), mar = c(4, 5, 3, 4))
plotGS(thca.filt, genesGS1, "type", main = names(rnkGS)[2], cex.lab = 2, las = 1)
plotGS(thca.filt, genesGS2, "type", main = names(rnkGS)[3], cex.lab = 2, las = 1)
```

calcualting z-scores

```{r}
pv <- pmin(pnorm(zS), 1 - pnorm(zS))
sum(pv < 0.05)
pvadj <- p.adjust(pv, method = "fdr")
DEgs <- names(pvadj)[which(pvadj < 0.01)]
length(DEgs)
head(DEgs, n = 3)
```


## Overlap gene sets
```{r}
library(GSVA)
gsov <- computeGeneSetsOverlap(gsc[DEgs], rownames(thca.filt))
trimask <- upper.tri(gsov)
rnkOv <- data.frame(gs1 = row(gsov)[trimask], gs2 = col(gsov)[trimask],
                    ov = gsov[trimask])
rnkOv <- rnkOv[order(rnkOv$ov, decreasing = TRUE), ]
rnkOv$gs1 <- rownames(gsov)[rnkOv$gs1]
rnkOv$gs2 <- rownames(gsov)[rnkOv$gs2]
sum(rnkOv$ov == 1)  ## how many pairs of gene sets are identical? Tecnicamente nos podemos centrar en estos solo.
sum(rnkOv$ov < 0.05)  ## how many pairs of gene sets share less than 5% of the genes?

```

For gene sets with more than about 20 genes, **X^2** follows a standard normal distribution. This score can be implemented using the function applyByCategory from the Category package:

```{r, message=FALSE}
library(Category)
xS <- applyByCategory(tGSgenes, Im, function(x) (sum((x - mean(x))^2) - (length(x) - 1))/(2 * 
    (length(x) - 1)))
#iterates through gene sets and calculates per gene set
rnkGS <- sort(abs(xS), decreasing = TRUE)
#For gene sets with more than about 20 genes, the **X2-score** also follow a standard normal distribution and we can compute p-values and adjust them to 1% FDR, as we did with the z-test:
pv <- pmin(pnorm(xS), 1 - pnorm(xS))
pvadj <- p.adjust(pv)
DEgsByScale <- names(pvadj)[which(pvadj < 0.01)]
length(DEgsByScale)
length(intersect(DEgs, DEgsByScale))
setdiff(DEgsByScale, DEgs)

topgs1genes <- colnames(Im)[which(Im[names(rnkGS)[2], ] == 1)]
topgs2genes <- colnames(Im)[which(Im[names(rnkGS)[3], ] == 1)]
topgs3genes <- colnames(Im)[which(Im[names(rnkGS)[4], ] == 1)]
par(mfrow = c(1, 3))
plotGS(thca.filt, topgs1genes, "type", main = names(rnkGS)[1], cex.lab = 2, las = 1)
plotGS(thca.filt, topgs2genes, "type", main = names(rnkGS)[2], cex.lab = 2, las = 1)
plotGS(thca.filt, topgs3genes, "type", main = names(rnkGS)[3], cex.lab = 2, las = 1)
```
